export interface RekapitulasiWilayahItem {
  id?: string | number
  kecamatan: string
  kelurahan: string
  total_siswa: number
  total_verified_rt: number
  persentase_verified: number
  total_mbr: number
  total_stunting: number
  total_gizi_kurang: number
  total_pmtas: number
  total_ddtk_selesai: number
  persentase_ddtk: number
}

// 27 Kelurahan Kota Tegal + Agregat Luar Kota Tegal
export const INITIAL_REKAPITULASI_WILAYAH: RekapitulasiWilayahItem[] = [
  // Margadana (7 Kelurahan)
  {
    kecamatan: "Margadana",
    kelurahan: "Cabawan",
    total_siswa: 54,
    total_verified_rt: 49,
    persentase_verified: 90.7,
    total_mbr: 18,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 38,
    total_ddtk_selesai: 50,
    persentase_ddtk: 92.6,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Kaligangsa",
    total_siswa: 68,
    total_verified_rt: 62,
    persentase_verified: 91.2,
    total_mbr: 22,
    total_stunting: 3,
    total_gizi_kurang: 4,
    total_pmtas: 52,
    total_ddtk_selesai: 64,
    persentase_ddtk: 94.1,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Kalinyamat Kulon",
    total_siswa: 62,
    total_verified_rt: 58,
    persentase_verified: 93.5,
    total_mbr: 19,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 45,
    total_ddtk_selesai: 60,
    persentase_ddtk: 96.8,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Krandon",
    total_siswa: 48,
    total_verified_rt: 43,
    persentase_verified: 89.6,
    total_mbr: 15,
    total_stunting: 1,
    total_gizi_kurang: 2,
    total_pmtas: 35,
    total_ddtk_selesai: 44,
    persentase_ddtk: 91.7,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Margadana",
    total_siswa: 75,
    total_verified_rt: 68,
    persentase_verified: 90.7,
    total_mbr: 24,
    total_stunting: 3,
    total_gizi_kurang: 5,
    total_pmtas: 58,
    total_ddtk_selesai: 71,
    persentase_ddtk: 94.7,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Pesurungan Lor",
    total_siswa: 56,
    total_verified_rt: 50,
    persentase_verified: 89.3,
    total_mbr: 17,
    total_stunting: 2,
    total_gizi_kurang: 2,
    total_pmtas: 42,
    total_ddtk_selesai: 52,
    persentase_ddtk: 92.9,
  },
  {
    kecamatan: "Margadana",
    kelurahan: "Sumurpanggang",
    total_siswa: 82,
    total_verified_rt: 74,
    persentase_verified: 90.2,
    total_mbr: 28,
    total_stunting: 4,
    total_gizi_kurang: 6,
    total_pmtas: 66,
    total_ddtk_selesai: 78,
    persentase_ddtk: 95.1,
  },

  // Tegal Barat (7 Kelurahan)
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Debong Lor",
    total_siswa: 52,
    total_verified_rt: 47,
    persentase_verified: 90.4,
    total_mbr: 14,
    total_stunting: 1,
    total_gizi_kurang: 2,
    total_pmtas: 40,
    total_ddtk_selesai: 49,
    persentase_ddtk: 94.2,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Kemandungan",
    total_siswa: 46,
    total_verified_rt: 41,
    persentase_verified: 89.1,
    total_mbr: 12,
    total_stunting: 1,
    total_gizi_kurang: 1,
    total_pmtas: 34,
    total_ddtk_selesai: 43,
    persentase_ddtk: 93.5,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Kraton",
    total_siswa: 94,
    total_verified_rt: 88,
    persentase_verified: 93.6,
    total_mbr: 26,
    total_stunting: 2,
    total_gizi_kurang: 4,
    total_pmtas: 78,
    total_ddtk_selesai: 90,
    persentase_ddtk: 95.7,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Muarareja",
    total_siswa: 78,
    total_verified_rt: 69,
    persentase_verified: 88.5,
    total_mbr: 31,
    total_stunting: 5,
    total_gizi_kurang: 7,
    total_pmtas: 64,
    total_ddtk_selesai: 72,
    persentase_ddtk: 92.3,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Pekauman",
    total_siswa: 64,
    total_verified_rt: 59,
    persentase_verified: 92.2,
    total_mbr: 16,
    total_stunting: 1,
    total_gizi_kurang: 3,
    total_pmtas: 50,
    total_ddtk_selesai: 61,
    persentase_ddtk: 95.3,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Pesurungan Kidul",
    total_siswa: 58,
    total_verified_rt: 53,
    persentase_verified: 91.4,
    total_mbr: 18,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 46,
    total_ddtk_selesai: 55,
    persentase_ddtk: 94.8,
  },
  {
    kecamatan: "Tegal Barat",
    kelurahan: "Tegalsari",
    total_siswa: 110,
    total_verified_rt: 102,
    persentase_verified: 92.7,
    total_mbr: 36,
    total_stunting: 4,
    total_gizi_kurang: 5,
    total_pmtas: 92,
    total_ddtk_selesai: 106,
    persentase_ddtk: 96.4,
  },

  // Tegal Selatan (7 Kelurahan)
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Bandung",
    total_siswa: 50,
    total_verified_rt: 45,
    persentase_verified: 90.0,
    total_mbr: 15,
    total_stunting: 2,
    total_gizi_kurang: 2,
    total_pmtas: 39,
    total_ddtk_selesai: 47,
    persentase_ddtk: 94.0,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kidul",
    total_siswa: 48,
    total_verified_rt: 44,
    persentase_verified: 91.7,
    total_mbr: 13,
    total_stunting: 1,
    total_gizi_kurang: 2,
    total_pmtas: 36,
    total_ddtk_selesai: 46,
    persentase_ddtk: 95.8,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Kulon",
    total_siswa: 55,
    total_verified_rt: 50,
    persentase_verified: 90.9,
    total_mbr: 16,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 43,
    total_ddtk_selesai: 52,
    persentase_ddtk: 94.5,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Debong Tengah",
    total_siswa: 65,
    total_verified_rt: 59,
    persentase_verified: 90.8,
    total_mbr: 20,
    total_stunting: 2,
    total_gizi_kurang: 4,
    total_pmtas: 51,
    total_ddtk_selesai: 62,
    persentase_ddtk: 95.4,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Kalinyamat Wetan",
    total_siswa: 72,
    total_verified_rt: 66,
    persentase_verified: 91.7,
    total_mbr: 23,
    total_stunting: 3,
    total_gizi_kurang: 4,
    total_pmtas: 58,
    total_ddtk_selesai: 68,
    persentase_ddtk: 94.4,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Randugunting",
    total_siswa: 125,
    total_verified_rt: 115,
    persentase_verified: 92.0,
    total_mbr: 34,
    total_stunting: 4,
    total_gizi_kurang: 6,
    total_pmtas: 104,
    total_ddtk_selesai: 120,
    persentase_ddtk: 96.0,
  },
  {
    kecamatan: "Tegal Selatan",
    kelurahan: "Tunon",
    total_siswa: 45,
    total_verified_rt: 40,
    persentase_verified: 88.9,
    total_mbr: 14,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 35,
    total_ddtk_selesai: 42,
    persentase_ddtk: 93.3,
  },

  // Tegal Timur (5 Kelurahan)
  {
    kecamatan: "Tegal Timur",
    kelurahan: "Kejambon",
    total_siswa: 88,
    total_verified_rt: 81,
    persentase_verified: 92.0,
    total_mbr: 22,
    total_stunting: 2,
    total_gizi_kurang: 3,
    total_pmtas: 72,
    total_ddtk_selesai: 84,
    persentase_ddtk: 95.5,
  },
  {
    kecamatan: "Tegal Timur",
    kelurahan: "Mangkukusuman",
    total_siswa: 60,
    total_verified_rt: 56,
    persentase_verified: 93.3,
    total_mbr: 11,
    total_stunting: 1,
    total_gizi_kurang: 2,
    total_pmtas: 48,
    total_ddtk_selesai: 58,
    persentase_ddtk: 96.7,
  },
  {
    kecamatan: "Tegal Timur",
    kelurahan: "Mintaragen",
    total_siswa: 96,
    total_verified_rt: 87,
    persentase_verified: 90.6,
    total_mbr: 30,
    total_stunting: 4,
    total_gizi_kurang: 5,
    total_pmtas: 80,
    total_ddtk_selesai: 91,
    persentase_ddtk: 94.8,
  },
  {
    kecamatan: "Tegal Timur",
    kelurahan: "Panggung",
    total_siswa: 130,
    total_verified_rt: 121,
    persentase_verified: 93.1,
    total_mbr: 38,
    total_stunting: 5,
    total_gizi_kurang: 7,
    total_pmtas: 110,
    total_ddtk_selesai: 125,
    persentase_ddtk: 96.2,
  },
  {
    kecamatan: "Tegal Timur",
    kelurahan: "Slerok",
    total_siswa: 104,
    total_verified_rt: 97,
    persentase_verified: 93.3,
    total_mbr: 27,
    total_stunting: 3,
    total_gizi_kurang: 4,
    total_pmtas: 89,
    total_ddtk_selesai: 100,
    persentase_ddtk: 96.2,
  },

  // Luar Kota Tegal
  {
    kecamatan: "Luar Kota Tegal",
    kelurahan: "Domisili Luar",
    total_siswa: 38,
    total_verified_rt: 22,
    persentase_verified: 57.9,
    total_mbr: 8,
    total_stunting: 1,
    total_gizi_kurang: 2,
    total_pmtas: 28,
    total_ddtk_selesai: 34,
    persentase_ddtk: 89.5,
  },
]
